matrix:
   include:
      - os: osx
        install: ./.travis/install.sh
        script: ./.travis/build.sh
      - os: linux
        dist: trusty
        addons:
           apt:
              packages:
                 - oracle-java8-installer
        sudo: true
        install: ./.travis/install.sh
        script: ./.travis/build.sh
